name: vscode-lean4 build

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build
        run: |
          npm ci
          npx lerna bootstrap --ci
          npm run build
          npx lerna run --scope=lean4 package
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: vscode-lean4
          path: 'vscode-lean4/lean4-*.vsix'
      - name: Lint
        run: npm run lint
      - name: Set path to elan
        run: |
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: Setup elan toolchain so lean can install new versions
        run: |
          curl -O --location https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh
          chmod u+x elan-init.sh
          ./elan-init.sh -y --default-toolchain leanprover/lean4:nightly
          echo Checking location "$HOME/.elan/bin"...
          ls -al "$HOME/.elan/bin"
          elan --version
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npx lerna run --scope=lean4 test
