name: vscode-lean4 build

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build
        run: |
          npm ci
          npx lerna bootstrap --ci
          npm run build
          npx lerna run --scope=lean4 package
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: vscode-lean4
          path: 'vscode-lean4/lean4-*.vsix'
      - name: Lint
        run: npm run lint
      - name: Test
        uses: GabrielBB/xvfb-action@v1
        run: |
          cd test
          npm install
          npm run test
